### ISSUE TITLE
[REQ] Add Mango Farm as RVN wallet

### ISSUE THREAD

**Issue by MangoFarmAssets** [trezor/community#10]
Ravencoin (RVN) is listed as a supported coin on the Trezor website.  https://trezor.io/coins/

Our web wallet (Mango Farm) now supports Trezor with RVN.  https://www.mangofarmassets.com

The Trezor site currently states “No wallet yet.”  May we get listed on the Trezor site as a RVN wallet?   

In addition, it is known to us that Trezor is supported by the RVN electrum fork.  We did not develop this but are passing it along in case you were not aware.  Perhaps this could be added as well.  https://github.com/traysi/electrum-raven/releases/

Thank you.

**Comment by prusnak** [comment]
Please send a pull request to this file: https://github.com/trezor/trezor-firmware/blob/ffde13000327e1c0b6f33cfed4c1348fdffdf90e/common/defs/coins_details.json

**Comment by MangoFarmAssets** [comment]
Will do thanks

On May 8, 2019, at 2:42 PM, Pavol Rusnak <notifications@github.com<mailto:notifications@github.com>> wrote:


Please send a pull request to this file: https://github.com/trezor/trezor-firmware/blob/ffde13000327e1c0b6f33cfed4c1348fdffdf90e/common/defs/coins_details.json

**Comment by MangoFarmAssets** [comment]
Added Mango Farm to wallets.json instead of coins_details.json per. instructions of @matejick here:  https://github.com/trezor/trezor-firmware/pull/142

I see that the wallets.json PR was merged.  Thank you. https://github.com/trezor/trezor-firmware/pull/145

If there is anything further we need to do to obtain a listing as a RVN wallet for Mango Farm and Electrum on the Trezor website (https://trezor.io/coins/) please advise. 

Thank you very much for a smooth process.

**Comment by prusnak** [comment]
> If there is anything further

No, just wait for the next website update

**Comment by MangoFarmAssets** [comment]
Thanks very much @prusnak
