### ISSUE TITLE
Remove link to non-authorized Amazon Reseller in Wiki

### ISSUE THREAD

**Issue by brianddk** [trezor/community#11]
In the [Ordering and Shipping FAQ](https://wiki.trezor.io/FAQ:Ordering_and_shipping) on wiki.trezor.io there is a [link to Amazon](https://wiki.trezor.io/FAQ:Ordering_and_shipping#Can_I_order_a_Trezor_from_Amazon.3F) that does not filter by merchant.  Amazon will (seemingly) randomly determine which merchant that particular link will arrive at.  This would lead a customer from a `trezor.io` site directly do a malicious Amazon merchant.

I'd suggest you link directly the the [Trezor Offical Amazon store](https://www.amazon.com/s?marketplaceID=ATVPDKIKX0DER&me=A25Z0IAI215API&merchant=A25Z0IAI215API&redirect=true) instead

**Comment by prusnak** [comment]
Forwarded to the wiki team, thanks Brian!
