### ISSUE TITLE
Unable to use Trezor wallet with Edge browser for Android

### ISSUE THREAD

**Issue by pacorreia** [trezor/community#12]
Hi team,

Not sure if this should be addressed by Support ticket, but here it goes.

I'm unable to use Trezor with Edge(latest) browser running on Android. I find it weird since it's running on Chromium base.

The page tells the browser is not supported and directs me to Chrome or FireFox.

Indeed it works on Chrome for mobile.

Could it have to do with simple User-agent identification?

Thanks

**Comment by prusnak** [comment]
We support only Chrome on Android. Please use that browser. We don't have resources to support any other browsers on Android. Thanks for understanding.

**Comment by pacorreia** [comment]
Thanks for the quick reply.

Of course I understand. I'm not a chrome user since edge adopted chromium and become faster and better. 

What if I can help supporting Edge? Since the base of Edge and Chrome is the same and both support webauthusb, I might be able to help. 

Just need some directions on the right repo to clone so I can provide a possible solution.

On Desktop Edge is fully supported and runs well without issues.
