### ISSUE TITLE
ChangeHero is a scam!

### ISSUE THREAD

**Issue by Janaka-Steph** [trezor/community#13]
Today I wanted to use the built-in Exchange feature in Trezor Suite converting BTC for ETH using [Change Hero](https://changehero.io). My transaction has been flagged as "suspicious" by their KYC department. Then you have two choices, either you go through the KYC procedure or you accept a refund minus 10% (see https://changehero.io/faq at the end).
It's not an easy choice but I decided to KYC. I provide my ID card plus a photo of me holding it as they ask. However they still refused to process the transaction and asked for an additional Source of Funds statement.
```
We would kindly ask you to provide us with the Source of Funds. It is the document that represents the origin of the funds that were sent to ChangeHero for the exchange (e.g. your trade history where it is clear that the account belongs to you, your purchase of sent crypto for fiat, bank statement or other documents that demonstrate the fact of you obtaining the amount of crypto in question).
```
You have to understand that those coins I sent were kept in cold storage for years. I genuinely have no idea of the exact source of funds. It is like asking where this bank note you have in your pocket comes from?
I was then forced to accept a partial refund with a 10% cut. 

So as you can see it is a clever scam. First the terms are totally abusive. But second you are screwed whatever you do. Nobody keep tracks of all payments, knowing where each utxo comes from, especially a cold storage that you don't touch often.

Change Hero should be removed from the Exchange providers on Trezor Suite!

**Comment by prusnak** [comment]
Thanks, forwarded to the Invity team, which is in charge of integrations
