### ISSUE TITLE
[REQ] Add Segwit Sign/Verify support to https://btc-bitcore1.trezor.io/messages/verify

### ISSUE THREAD

**Issue by brianddk** [trezor/community#4]
Please add support sign/verify support for P2SH-segwit and bech32-segwit address.  This would allow a Trezor HW Wallet owner to sign messages and direct non-Trezor wallet owners to https://btc-bitcore1.trezor.io/messages/verify, or perhaps a beta site like https://btc-bitcore1.trezor.io/messages/beta-verify

**Comment by prusnak** [comment]
We won't be adding such features to Insight Block Explorer. Sign Message and Verify message is available from TREZOR Web Wallet UI.

**Comment by brianddk** [comment]
Understood... Thx for the quick reply.

**Comment by prusnak** [comment]
You might want to open upstream issue here: https://github.com/bitpay/insight/

**Comment by brianddk** [comment]
Already looking for spot where they do the verify function presently... I'll post here once I get the PR filed... may take a while.

**Comment by brianddk** [comment]
Found where to bolt it... I'll look into it later.  Leaving this hear in case I get pulled into other things.

https://github.com/bitpay/bitcore-message/blob/master/lib/message.js
