### ISSUE TITLE
[REQ] Implement RBF for BTC on beta-wallet.trezor.io

### ISSUE THREAD

**Issue by brianddk** [trezor/community#5]
Looking through the JS console log on beta-wallet.trezor.io, it appears that the sequence number for inputs on TXNs are still listed as `4294967295` or `0xFFFFFFFF`.  RBF ([BIP 125](https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki)) suggests decrementing the sequence for inputs to `4294967294` (`0xFFFFFFFE`) or lower to explicitly opt-in to RBF protocols.  Ideally this would be a checkbox on the *Send* interface that would allow RBF (off/on) for the particular TXN.

These assessments could be incorrect since I was hesitant to spend the amount of money required to put an actual TXN on the network.  I simply tried to see what `trezor.js` was sending over the wire to the FW for signing and deduced that RBF appeared to be off (not opt-in).

**Comment by brianddk** [comment]
For future readers... this feature is already [implemented](https://github.com/trezor/python-trezor/pull/192) in the [python-trezor](https://github.com/trezor/python-trezor) library, and I've verified it on BTC Testnet.

**Comment by prusnak** [comment]
The problem with RBF is not sending a RBF transaction, but rather meaningfully creating a new (replacing) one. This is a work-in progress for web wallet and we want to get the UI right, so it is not confusing for user.

**Comment by brianddk** [comment]
Understood... Having it on the roadmap is good news.

Thx

**Comment by koemeet** [comment]
any progress?
