### ISSUE TITLE
Change the links for the documentation for community and gitter.

### ISSUE THREAD

**Issue by strmci** [trezor/community#7]
Please change the links of docs to:
https://wiki.trezor.io/User_manual
https://wiki.trezor.io/Developers_guide
https://wiki.trezor.io/Security
https://wiki.trezor.io/FAQ

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/community/commit/905ddec3ab977293c7eb758aef1c8ead36cd86c3
