### ISSUE TITLE
Javascript Port of Slip--39

### ISSUE THREAD

**Issue by itsMikeLowrey** [trezor/community#9]
I am currently working on porting the slip--39 to javascript. I plan to host it as a npm library an expose the gen-mnemonic interface. I am just to the point of working on the c code interface, but I wanted to reach out about having the code reviewed when it is completed. I will have a testing suite but I wanted to reach out ahead of time and see if there was a process to go through to get code like this reviewed by anyone at trezor or in the community before its released into the wild.

**Comment by prusnak** [comment]
Please open the issue in this repo once you are ready for review: https://github.com/trezor/trezor-firmware
